

##### PRELIMINARIES ##### 

library(targets)
library(tarchetypes)
library(future)

plan(multisession)

source("R/functions.R")

tar_option_set(
  packages = c(
    "magrittr",
    "tidyverse",
    "haven",
    "mice",
    "miceadds",
    "miselect",
    "psych",
    "OpenMx",
    "readxl", 
    "umx",
    "lavaan",
    "koRpus.lang.en",
    "koRpus",
    "LanguageToolR",
    "SuperLearner",
    "keras",
    "tensorflow",
    "tfdatasets",
    "data.table"
  ),
  error = "workspace"
)


##### TARGETS ASSOCIATED WITH LOADING THE DATA #####

targets_load_data <- list(tar_target(ncds_essays, 
                                     read_essays(folder = "data/essays")),
                          tar_target(mapping_df, read_datalist(path = "data/variables.xlsx")),
                          tar_target(ncds_1_2_3,
                                     read_ncds(file = "data/ncds_1_2_3/ncds0123.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_4,
                                     read_ncds(file = "data/ncds_4/ncds4.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_5,
                                     read_ncds(file = "data/ncds_5/ncds5cmi.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_6,
                                     read_ncds(file = "data/ncds_6/ncds6.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_7,
                                     read_ncds(file = "data/ncds_7/ncds7.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_8,
                                     read_ncds(file = "data/ncds_8/ncds_2008_followup.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_9,
                                     read_ncds(file = "data/ncds_9/ncds_2013_flatfile.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_occ_2,
                                     read_ncds(file = "data/ncds_occ_coding/ncds2_occupation_coding_father.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_occ_5,
                                     read_ncds(file = "data/ncds_occ_coding/ncds5_occupation_coding_cm.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_occ_6,
                                     read_ncds(file = "data/ncds_occ_coding/ncds6_occupation_coding_cm.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_occ_7,
                                     read_ncds(file = "data/ncds_occ_coding/ncds7_occupation_coding_cm.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(ncds_occ_8,
                                     read_ncds(file = "data/ncds_occ_coding/ncds8_occupation_coding_cm.dta",
                                               varlist = 
                                                 tolower(mapping_df$variable))),
                          tar_target(camsis_data, read_camsis(path = "data/camsis/gb71co70.dta")),
                          tar_target(gene_data, read_gene_data),
                          tar_target(occupation_aspiration_mapping, read_occupation_aspiration_mapping(path = "data/occupation_aspiration_mapping.xlsx")))


##### TARGETS ASSOCIATED WITH ESSAYS ####

targets_essay <- list(tar_target(tokenized_essays, tokenize_essays(ncds_essays)),
                      tar_target(spelling_errors, get_spelling_error_metrics(ncds_essays, path = "data/spelling_mistakes.csv")),
                      tar_target(readability_metrics, calculate_readability_metrics(ncds_essays, tokenized_essays)),
                      tar_target(salat_metrics, get_salat_metrics(ncds_essays,
                                                                  taaled_1 = "data/salat_metrics/essays_1_taaled.csv",
                                                                  taaled_2 = "data/salat_metrics/essays_2_taaled.csv",
                                                                  taaled_3 = "data/salat_metrics/essays_3_taaled.csv",
                                                                  taales_1 = "data/salat_metrics/essays_1_taales.csv",
                                                                  taales_2 = "data/salat_metrics/essays_2_taales.csv",
                                                                  taales_3 = "data/salat_metrics/essays_3_taales.csv",
                                                                  seance_1 = "data/salat_metrics/essays_1_seance.csv",
                                                                  seance_2 = "data/salat_metrics/essays_2_seance.csv",
                                                                  seance_3 = "data/salat_metrics/essays_3_seance.csv")),
                      tar_target(roberta_embeddings, get_roberta_embeddings(ncds_essays)),
                      tar_target(gpt_embeddings, get_gpt_embeddings(ncds_essays)),
                      tar_target(gpt4_embeddings, get_gpt_embeddings(ncds_essays)),
                      tar_target(essay_data, create_essay_variables(salat_metrics, readability_metrics, spelling_errors, gpt_embeddings))
                      )

##### TARGETS ASSOCIATED WITH CLEANING THE DATA #####

targets_clean_data <- list(tar_target(teacher_variables, c("s2_te_general_knowledge", "s2_te_number_work",
                                      "s2_te_use_of_books", "s2_te_oral_ability",
                                      "s2_te_poor_hand_control", "s2_te_squirmy",
                                      "s2_te_poor_coordination", "s2_te_hardly_ever_still",
                                      "s2_te_poor_speech", "s2_te_inconsequential_behavior",
                                      "s2_te_miscellneous_symptoms", "s2_te_anxiety_adults",
                                      "s2_te_anxiety_children", "s2_te_hostility_children",
                                      "s2_te_writing_off_adults", "s2_te_misc",
                                      "s2_te_hostility_adults", "s2_te_restlessness",
                                      "s2_te_unforthcomingness","s2_te_depression",
                                      "s2_te_withdrawal")),
                            tar_target(sociological_variables, c("s0_co_male", "s3_pa_father_edu", "s3_pa_mother_edu", "s0_mo_class_mother_husband", "s0_mo_persons_per_room", "s2_pa_nssec_father", "s0_mo_class_mother_father")),
                            tar_target(gene_variables, colnames(gene_data)[-1]),
                            tar_target(essay_variables, colnames(essay_data)[-1]),
                            tar_target(salat_metrics_variables, colnames(salat_metrics %>% dplyr::select(dplyr::one_of(colnames(essay_data))))[-1]),
                            tar_target(readability_metrics_variables, colnames(readability_metrics %>% dplyr::select(dplyr::one_of(colnames(essay_data))))[-c(1:2)]), 
                            tar_target(spelling_errors_variables, colnames(spelling_errors %>% dplyr::select(dplyr::one_of(colnames(essay_data))))[-1]), 
                            tar_target(gpt_embeddings_variables, colnames(gpt_embeddings %>% dplyr::select(dplyr::one_of(colnames(essay_data))))[-1]), 
                            tar_target(gpt4_embeddings_variables, colnames(gpt4_embeddings)[-1]), 
                            tar_target(roberta_embeddings_variables, paste0("roberta_dim_", 1:768)), 
                            tar_target(mmg_variables, c(gene_variables, essay_variables, teacher_variables)),
                            tar_target(mmg_edu_variables, c(gene_variables, essay_variables, teacher_variables, "s5_co_highest_edu")),
                            tar_target(mmg_cog_variables, c(gene_variables, essay_variables, teacher_variables, "s2_co_factor_ability")),
                            tar_target(cog_variables, c("s2_co_factor_ability", 
                                                        "s2_co_verbal_ability",  "s2_co_nonverbal_ability",
                                                        "s2_co_reading_ability",  "s2_co_mathematics_ability",
                                                        "s3_co_reading_ability",  "s3_co_mathematics_ability")),
                            tar_target(noncog_variables, c("s2_co_aspiration_camsis", 
                                                           "s3_co_factor_scholastic_motivation", 
                                                           "s3_te_factor_externalizing",  "s3_te_factor_internalizing")),
                            tar_target(cog_noncog_variables, c(cog_variables, noncog_variables)),
                            tar_target(bfi_variables, c("s8_co_extraversion",  
                                                        "s8_co_agreeableness",  "s8_co_conscientiousness",
                                                        "s8_co_neuroticism",  "s8_co_openness")),
                            tar_target(confounder_variables, c("s3_pa_edu", "s3_co_height", "s0_co_male", "s0_mo_birthweight")),
                            tar_target(social_outcomes, c("s5_co_highest_edu")),
                            tar_target(all_vars, c(teacher_variables, gene_variables, 
                                                  essay_variables, cog_noncog_variables,
                                                  social_outcomes, confounder_variables)),
                            tar_target(all_outcomes, c(cog_noncog_variables,social_outcomes)),
                            tar_target(ncds_1_to_9, combine_ncds(ncds_1_2_3, ncds_4, 
                                                                ncds_5, ncds_6, 
                                                                ncds_7, ncds_8, 
                                                                ncds_9, ncds_occ_2,
                                                                ncds_occ_5, ncds_occ_6,
                                                                ncds_occ_7, ncds_occ_8)),
                           tar_target(ncds_1_to_9_cleaned, clean_ncds(ncds_1_to_9, mapping_df)),
                           tar_target(aspiration_data, create_aspirations(ncds_1_to_9, camsis_data, occupation_aspiration_mapping)),
                           tar_target(factor_data, create_factors(ncds_1_to_9_cleaned)),
                           tar_target(ncds_complete, get_complete_ncds(ncds_1_to_9_cleaned, factor_data, aspiration_data, essay_data, gene_data)),
                           tar_target(ncds_complete_mmg, find_full_overlap(ncds_complete, mmg_edu_variables)),
                           tar_target(ncds_complete_mmg_cog, find_full_overlap(ncds_complete, mmg_cog_variables)),
                           tar_target(ncds_complete_all_overlap, find_full_overlap(ncds_complete, all_vars))
                            
) 

##### TARGETS ASSOCIATED WITH RUNNING THE MODELS #####

targets_superlearner <- list(tar_target(essay_superlearner_overlap, get_general_superlearner_cv_model(all_outcomes, essay_variables,
                                                                                            ncds_complete_all_overlap),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(gene_superlearner_overlap, get_general_superlearner_cv_model(all_outcomes, gene_variables,
                                                                                                       ncds_complete_all_overlap),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_superlearner_overlap, get_general_superlearner_cv_model(all_outcomes, teacher_variables,
                                                                                                       ncds_complete_all_overlap),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(essay_genes_superlearner_overlap, get_general_superlearner_cv_model(all_outcomes, c(essay_variables, gene_variables),
                                                                                                         ncds_complete_all_overlap),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(essay_teacher_superlearner_overlap, get_general_superlearner_cv_model(all_outcomes, c(essay_variables, teacher_variables),
                                                                                                        ncds_complete_all_overlap),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_genes_superlearner_overlap, get_general_superlearner_cv_model(all_outcomes, c(teacher_variables,gene_variables),
                                                                                                           ncds_complete_all_overlap),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner_overlap, get_general_superlearner_cv_model(all_outcomes, c(teacher_variables,gene_variables, essay_variables),
                                                                                                                 ncds_complete_all_overlap),
                                        pattern = all_outcomes, iteration = "list"),
                             
                             tar_target(cog_superlearner_social_overlap, get_general_superlearner_cv_model(social_outcomes, cog_variables, ncds_complete_all_overlap),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(noncog_superlearner_social_overlap, get_general_superlearner_cv_model(social_outcomes, noncog_variables, ncds_complete_all_overlap),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(birthweight_superlearner_social_overlap, get_general_superlearner_cv_model(social_outcomes, "s0_mo_birthweight", ncds_complete_all_overlap),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(height_superlearner_social_overlap, get_general_superlearner_cv_model(social_outcomes, "s3_co_height", ncds_complete_all_overlap),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(pedu_superlearner_social_overlap, get_general_superlearner_cv_model(social_outcomes, "s3_pa_edu", ncds_complete_all_overlap %>% dplyr::mutate(s3_pa_edu = as.numeric(s3_pa_edu))),
                                        pattern = social_outcomes, iteration = "list"),
                             
                             tar_target(salat_metrics_superlearner, get_general_superlearner_cv_model(all_outcomes, salat_metrics_variables,
                                                                                              ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(readability_metrics_superlearner, get_general_superlearner_cv_model(all_outcomes, readability_metrics_variables,
                                                                                              ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(spelling_errors_superlearner, get_general_superlearner_cv_model(all_outcomes, spelling_errors_variables,
                                                                                              ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(spelling_salat_readability_superlearner, get_general_superlearner_cv_model(all_outcomes, c(salat_metrics_variables, readability_metrics_variables, spelling_errors_variables),
                                                                                                        ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(gpt_embeddings_superlearner, get_general_superlearner_cv_model(all_outcomes, gpt_embeddings_variables,
                                                                                              ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(roberta_embeddings_superlearner, get_general_superlearner_cv_model(all_outcomes, roberta_embeddings_variables,
                                                                                                       ncds_complete %>% dplyr::inner_join(roberta_embeddings, by = c("ncdsid" = "id"))),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(gpt4_embeddings_superlearner, get_general_superlearner_cv_model(all_outcomes, gpt4_embeddings_variables,
                                                                                                           ncds_complete %>% dplyr::select(-dplyr::starts_with("embedding")) %>% dplyr::inner_join(gpt4_embeddings, by = c("ncdsid" = "id"))),
                                        pattern = all_outcomes, iteration = "list"),
                             
                             
                             tar_target(essay_superlearner, get_general_superlearner_cv_model(all_outcomes, essay_variables,
                                                                                              ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(gene_superlearner, get_general_superlearner_cv_model(all_outcomes, gene_variables,
                                                                                             ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_superlearner, get_general_superlearner_cv_model(all_outcomes, teacher_variables,
                                                                                                ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(essay_genes_superlearner, get_general_superlearner_cv_model(all_outcomes, c(essay_variables, gene_variables),
                                                                                                    ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(essay_teacher_superlearner, get_general_superlearner_cv_model(all_outcomes, c(essay_variables, teacher_variables),
                                                                                                      ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_genes_superlearner, get_general_superlearner_cv_model(all_outcomes, c(teacher_variables,gene_variables),
                                                                                                      ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner, get_general_superlearner_cv_model(all_outcomes, c(teacher_variables,gene_variables, essay_variables),
                                                                                                            ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             
                             tar_target(sociological_superlearner, get_general_superlearner_cv_model(all_outcomes, c(sociological_variables),
                                                                                                            ncds_complete %>% 
                                                                                                       dplyr::mutate_at(dplyr::vars(sociological_variables), as.numeric)),
                                        pattern = all_outcomes, iteration = "list"),
                             
                             tar_target(text_length, get_lm_cv_model(all_outcomes, "nwords",
                                                                  ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             
                             tar_target(essay_lm, get_lm_cv_model(all_outcomes, essay_variables,
                                                                                              ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(gene_lm, get_lm_cv_model(all_outcomes, gene_variables,
                                                                                             ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_lm, get_lm_cv_model(all_outcomes, teacher_variables,
                                                                                                ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(essay_genes_lm, get_lm_cv_model(all_outcomes, c(essay_variables, gene_variables),
                                                                                                    ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(essay_teacher_lm, get_lm_cv_model(all_outcomes, c(essay_variables, teacher_variables),
                                                                                                      ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_genes_lm, get_lm_cv_model(all_outcomes, c(teacher_variables,gene_variables),
                                                                                                      ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             tar_target(teacher_genes_essay_lm, get_lm_cv_model(all_outcomes, c(teacher_variables,gene_variables, essay_variables),
                                                                                                            ncds_complete),
                                        pattern = all_outcomes, iteration = "list"),
                             
                             tar_target(essay_bfi_superlearner, get_general_superlearner_cv_model(bfi_variables, essay_variables,
                                                                                              ncds_complete),
                                        pattern = bfi_variables, iteration = "list"),
                             tar_target(gene_bfi_superlearner, get_general_superlearner_cv_model(bfi_variables, gene_variables,
                                                                                             ncds_complete),
                                        pattern = bfi_variables, iteration = "list"),
                             tar_target(teacher_bfi_superlearner, get_general_superlearner_cv_model(bfi_variables, teacher_variables,
                                                                                                ncds_complete),
                                        pattern = bfi_variables, iteration = "list"),
                             tar_target(teacher_genes_essay_bfi_superlearner, get_general_superlearner_cv_model(bfi_variables, c(teacher_variables,gene_variables, essay_variables),
                                                                                                            ncds_complete),
                                        pattern = bfi_variables, iteration = "list"),
                             
                             
                             tar_target(essay_superlearner_mmg, get_general_superlearner_cv_model(social_outcomes, essay_variables,
                                                                                                  ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(gene_superlearner_mmg, get_general_superlearner_cv_model(social_outcomes, gene_variables,
                                                                                                 ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(teacher_superlearner_mmg, get_general_superlearner_cv_model(social_outcomes, teacher_variables,
                                                                                                    ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(essay_genes_superlearner_mmg, get_general_superlearner_cv_model(social_outcomes, c(essay_variables, gene_variables),
                                                                                                        ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(essay_teacher_superlearner_mmg, get_general_superlearner_cv_model(social_outcomes, c(essay_variables, teacher_variables),
                                                                                                          ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(teacher_genes_superlearner_mmg, get_general_superlearner_cv_model(social_outcomes, c(teacher_variables,gene_variables),
                                                                                                          ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner_mmg, get_general_superlearner_cv_model(social_outcomes, c(teacher_variables,gene_variables, essay_variables),
                                                                                                                ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             
                             tar_target(essay_superlearner_mmg_lm, get_lm_cv_model(social_outcomes, essay_variables,
                                                                                                  ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(gene_superlearner_mmg_lm, get_lm_cv_model(social_outcomes, gene_variables,
                                                                                                 ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(teacher_superlearner_mmg_lm, get_lm_cv_model(social_outcomes, teacher_variables,
                                                                                                    ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(essay_genes_superlearner_mmg_lm, get_lm_cv_model(social_outcomes, c(essay_variables, gene_variables),
                                                                                                        ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(essay_teacher_superlearner_mmg_lm, get_lm_cv_model(social_outcomes, c(essay_variables, teacher_variables),
                                                                                                          ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(teacher_genes_superlearner_mmg_lm, get_lm_cv_model(social_outcomes, c(teacher_variables,gene_variables),
                                                                                                          ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner_mmg_lm, get_lm_cv_model(social_outcomes, c(teacher_variables,gene_variables, essay_variables),
                                                                                                                ncds_complete_mmg),
                                        pattern = social_outcomes, iteration = "list"),
                            
                             tar_target(essay_superlearner_cog_mmg, get_general_superlearner_cv_model("s2_co_factor_ability", essay_variables,
                                                                                                      ncds_complete_mmg_cog)),
                             tar_target(gene_superlearner_cog_mmg, get_general_superlearner_cv_model("s2_co_factor_ability", gene_variables,
                                                                                                     ncds_complete_mmg_cog)),
                             tar_target(teacher_superlearner_cog_mmg, get_general_superlearner_cv_model("s2_co_factor_ability", teacher_variables,
                                                                                                        ncds_complete_mmg_cog)),
                             tar_target(essay_genes_superlearner_cog_mmg, get_general_superlearner_cv_model("s2_co_factor_ability", c(essay_variables, gene_variables),
                                                                                                            ncds_complete_mmg_cog)),
                             tar_target(essay_teacher_superlearner_cog_mmg, get_general_superlearner_cv_model("s2_co_factor_ability", c(essay_variables, teacher_variables),
                                                                                                              ncds_complete_mmg_cog)),
                             tar_target(teacher_genes_superlearner_cog_mmg, get_general_superlearner_cv_model("s2_co_factor_ability", c(teacher_variables,gene_variables),
                                                                                                              ncds_complete_mmg_cog)),
                             tar_target(teacher_genes_essay_superlearner_cog_mmg, get_general_superlearner_cv_model("s2_co_factor_ability", c(teacher_variables,gene_variables, essay_variables),
                                                                                                                    ncds_complete_mmg_cog)),
                             
                             tar_target(cog_superlearner_social, get_general_superlearner_cv_model(social_outcomes, cog_variables, ncds_complete),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(noncog_superlearner_social, get_general_superlearner_cv_model(social_outcomes, noncog_variables, ncds_complete),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(birthweight_superlearner_social, get_general_superlearner_cv_model(social_outcomes, "s0_mo_birthweight", ncds_complete),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(height_superlearner_social, get_general_superlearner_cv_model(social_outcomes, "s3_co_height", ncds_complete),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(pedu_superlearner_social, get_general_superlearner_cv_model(social_outcomes, "s3_pa_edu", ncds_complete %>% dplyr::mutate(s3_pa_edu = as.numeric(s3_pa_edu))),
                                        pattern = social_outcomes, iteration = "list"),
                             
                             
                             tar_target(sociological_superlearner_social_lm, get_lm_cv_model(social_outcomes, c(sociological_variables),
                                                                                      ncds_complete %>% 
                                                                                        dplyr::mutate_at(dplyr::vars(sociological_variables), as.numeric)),
                                        pattern = social_outcomes, iteration = "list"),
                             
                             tar_target(cog_superlearner_social_lm, get_lm_cv_model(social_outcomes, "s2_co_factor_ability", ncds_complete),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(noncog_superlearner_social_lm, get_lm_cv_model(social_outcomes, noncog_variables, ncds_complete),
                                        pattern = social_outcomes, iteration = "list"),
                             
                             tar_target(cog_superlearner_social_lm_overlap, get_lm_cv_model(social_outcomes, "s2_co_factor_ability", ncds_complete_all_overlap),
                                        pattern = social_outcomes, iteration = "list"),
                             tar_target(noncog_superlearner_social_lm_overlap, get_lm_cv_model(social_outcomes, noncog_variables, ncds_complete_all_overlap),
                                        pattern = social_outcomes, iteration = "list"),
                             
                             tar_target(essay_superlearner_overlap_metrics, get_cv_superlearner_metrics(essay_superlearner_overlap),
                                        pattern = essay_superlearner_overlap, iteration = "list"),
                             tar_target(gene_superlearner_overlap_metrics, get_cv_superlearner_metrics(gene_superlearner_overlap),
                                        pattern = gene_superlearner_overlap, iteration = "list"),
                             tar_target(teacher_superlearner_overlap_metrics, get_cv_superlearner_metrics(teacher_superlearner_overlap),
                                        pattern = teacher_superlearner_overlap, iteration = "list"),
                             tar_target(essay_genes_superlearner_overlap_metrics, get_cv_superlearner_metrics(essay_genes_superlearner_overlap),
                                        pattern = essay_genes_superlearner_overlap, iteration = "list"),
                             tar_target(essay_teacher_superlearner_overlap_metrics, get_cv_superlearner_metrics(essay_teacher_superlearner_overlap),
                                        pattern = essay_teacher_superlearner_overlap, iteration = "list"),
                             tar_target(teacher_genes_superlearner_overlap_metrics, get_cv_superlearner_metrics(teacher_genes_superlearner_overlap),
                                        pattern = teacher_genes_superlearner_overlap, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner_overlap_metrics, get_cv_superlearner_metrics(teacher_genes_essay_superlearner_overlap),
                                        pattern = teacher_genes_essay_superlearner_overlap, iteration = "list"),

                             tar_target(essay_superlearner_mmg_metrics, get_cv_superlearner_metrics(essay_superlearner_mmg),
                                        pattern = essay_superlearner_mmg, iteration = "list"),
                             tar_target(gene_superlearner_mmg_metrics, get_cv_superlearner_metrics(gene_superlearner_mmg),
                                        pattern = gene_superlearner_mmg, iteration = "list"),
                             tar_target(teacher_superlearner_mmg_metrics, get_cv_superlearner_metrics(teacher_superlearner_mmg),
                                        pattern = teacher_superlearner_mmg, iteration = "list"),
                             tar_target(essay_genes_superlearner_mmg_metrics, get_cv_superlearner_metrics(essay_genes_superlearner_mmg),
                                        pattern = essay_genes_superlearner_mmg, iteration = "list"),
                             tar_target(essay_teacher_superlearner_mmg_metrics, get_cv_superlearner_metrics(essay_teacher_superlearner_mmg),
                                        pattern = essay_teacher_superlearner_mmg, iteration = "list"),
                             tar_target(teacher_genes_superlearner_mmg_metrics, get_cv_superlearner_metrics(teacher_genes_superlearner_mmg),
                                        pattern = teacher_genes_superlearner_mmg, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner_mmg_metrics, get_cv_superlearner_metrics(teacher_genes_essay_superlearner_mmg),
                                        pattern = teacher_genes_essay_superlearner_mmg, iteration = "list"),
                             
                             tar_target(essay_superlearner_bfi_metrics, get_cv_superlearner_metrics(essay_bfi_superlearner),
                                        pattern = essay_bfi_superlearner, iteration = "list"),
                             tar_target(gene_superlearner_bfi_metrics, get_cv_superlearner_metrics(gene_bfi_superlearner),
                                        pattern = gene_bfi_superlearner, iteration = "list"),
                             tar_target(teacher_superlearner_bfi_metrics, get_cv_superlearner_metrics(teacher_bfi_superlearner),
                                        pattern = teacher_bfi_superlearner, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner_bfi_metrics, get_cv_superlearner_metrics(teacher_genes_essay_bfi_superlearner),
                                        pattern = teacher_genes_essay_bfi_superlearner, iteration = "list"),
                             
                             tar_target(essay_superlearner_cog_mmg_metrics, get_cv_superlearner_metrics(essay_superlearner_cog_mmg)),
                             tar_target(gene_superlearner_cog_mmg_metrics, get_cv_superlearner_metrics(gene_superlearner_cog_mmg)),
                             tar_target(teacher_superlearner_cog_mmg_metrics, get_cv_superlearner_metrics(teacher_superlearner_cog_mmg)),
                             tar_target(essay_genes_superlearner_cog_mmg_metrics, get_cv_superlearner_metrics(essay_genes_superlearner_cog_mmg)),
                             tar_target(essay_teacher_superlearner_cog_mmg_metrics, get_cv_superlearner_metrics(essay_teacher_superlearner_cog_mmg)),
                             tar_target(teacher_genes_superlearner_cog_mmg_metrics, get_cv_superlearner_metrics(teacher_genes_superlearner_cog_mmg)),
                             tar_target(teacher_genes_essay_superlearner_cog_mmg_metrics, get_cv_superlearner_metrics(teacher_genes_essay_superlearner_cog_mmg)),
                             
                             tar_target(essay_superlearner_metrics, get_cv_superlearner_metrics(essay_superlearner),
                                        pattern = essay_superlearner, iteration = "list"),
                             tar_target(gene_superlearner_metrics, get_cv_superlearner_metrics(gene_superlearner),
                                        pattern = gene_superlearner, iteration = "list"),
                             tar_target(teacher_superlearner_metrics, get_cv_superlearner_metrics(teacher_superlearner),
                                        pattern = teacher_superlearner, iteration = "list"),
                             tar_target(essay_genes_superlearner_metrics, get_cv_superlearner_metrics(essay_genes_superlearner),
                                        pattern = essay_genes_superlearner, iteration = "list"),
                             tar_target(essay_teacher_superlearner_metrics, get_cv_superlearner_metrics(essay_teacher_superlearner),
                                        pattern = essay_teacher_superlearner, iteration = "list"),
                             tar_target(teacher_genes_superlearner_metrics, get_cv_superlearner_metrics(teacher_genes_superlearner),
                                        pattern = teacher_genes_superlearner, iteration = "list"),
                             tar_target(teacher_genes_essay_superlearner_metrics, get_cv_superlearner_metrics(teacher_genes_essay_superlearner),
                                        pattern = teacher_genes_essay_superlearner, iteration = "list"),
                             
                             tar_target(sociological_superlearner_metrics, get_cv_superlearner_metrics(sociological_superlearner),
                                        pattern = sociological_superlearner, iteration = "list"),

                             tar_target(essay_lm_metrics, get_cv_lm_metrics(essay_lm),
                                        pattern = essay_lm, iteration = "list"),
                             tar_target(gene_lm_metrics, get_cv_lm_metrics(gene_lm),
                                        pattern = gene_lm, iteration = "list"),
                             tar_target(teacher_lm_metrics, get_cv_lm_metrics(teacher_lm),
                                        pattern = teacher_lm, iteration = "list"),
                             tar_target(essay_genes_lm_metrics, get_cv_lm_metrics(essay_genes_lm),
                                        pattern = essay_genes_lm, iteration = "list"),
                             tar_target(essay_teacher_lm_metrics, get_cv_lm_metrics(essay_teacher_lm),
                                        pattern = essay_teacher_lm, iteration = "list"),
                             tar_target(teacher_genes_lm_metrics, get_cv_lm_metrics(teacher_genes_lm),
                                        pattern = teacher_genes_lm, iteration = "list"),
                             tar_target(teacher_genes_essay_lm_metrics, get_cv_lm_metrics(teacher_genes_essay_lm),
                                        pattern = teacher_genes_essay_lm, iteration = "list"),
                             
                             tar_target(cog_superlearner_social_overlap_metrics, get_cv_superlearner_metrics(cog_superlearner_social_overlap),
                                        pattern = cog_superlearner_social_overlap, iteration = "list"),
                             tar_target(noncog_superlearner_social_overlap_metrics, get_cv_superlearner_metrics(noncog_superlearner_social_overlap),
                                        pattern = noncog_superlearner_social_overlap, iteration = "list"),
                             tar_target(birthweight_superlearner_social_overlap_metrics, get_cv_superlearner_metrics(birthweight_superlearner_social_overlap),
                                        pattern = birthweight_superlearner_social_overlap, iteration = "list"),
                             tar_target(height_superlearner_social_overlap_metrics, get_cv_superlearner_metrics(height_superlearner_social_overlap),
                                        pattern = height_superlearner_social_overlap, iteration = "list"),
                             tar_target(pedu_superlearner_social_overlap_metrics, get_cv_superlearner_metrics(pedu_superlearner_social_overlap),
                                        pattern = pedu_superlearner_social_overlap, iteration = "list"),
                             
                             tar_target(cog_superlearner_social_metrics, get_cv_superlearner_metrics(cog_superlearner_social),
                                        pattern = cog_superlearner_social, iteration = "list"),
                             tar_target(noncog_superlearner_social_metrics, get_cv_superlearner_metrics(noncog_superlearner_social),
                                        pattern = noncog_superlearner_social, iteration = "list"),
                             tar_target(birthweight_superlearner_social_metrics, get_cv_superlearner_metrics(birthweight_superlearner_social),
                                        pattern = birthweight_superlearner_social, iteration = "list"),
                             tar_target(height_superlearner_social_metrics, get_cv_superlearner_metrics(height_superlearner_social),
                                        pattern = height_superlearner_social, iteration = "list"),
                             tar_target(pedu_superlearner_social_metrics, get_cv_superlearner_metrics(pedu_superlearner_social),
                                        pattern = pedu_superlearner_social, iteration = "list"),
                             
                             tar_target(sociological_superlearner_social_lm_metrics, get_cv_superlearner_metrics(sociological_superlearner_social_lm),
                                        pattern = sociological_superlearner_social_lm, iteration = "list"),
                             tar_target(cog_superlearner_social_lm_metrics, get_cv_superlearner_metrics(cog_superlearner_social_lm),
                                        pattern = cog_superlearner_social_lm, iteration = "list"),
                             tar_target(noncog_superlearner_social_lm_metrics, get_cv_superlearner_metrics(noncog_superlearner_social_lm),
                                        pattern = noncog_superlearner_social_lm, iteration = "list")
) 






tar_pipeline(c(targets_load_data, targets_essay, targets_clean_data, targets_superlearner))


